### PR TITLE
[#762] add include dir option of deps for compiler diagnostics

### PR DESCRIPTION
**Pull request by luos**
If an erlang file has a hrl included the compiler diagnostics raises an
error because it is not included in the arguments for the compile call.

Fix needs that the dependency directory is configured correctly in the `erlang_ls.config` file. 

Related #762

### CODE REVIEW

**Comment by luos** [comment]
Hi,

Should I add an example project under `priv`?

**Comment by alanz** [comment]
> Should I add an example project under priv?

If possible do it under `tests/els_diagnostics_SUITE_data/`.  We only use `priv` for stuff that is so broken that rebar cant use it.

*Or*, modify one of the existing projects under `priv`.  But probably better to add a fresh one, for the specific problem.

**Comment by luos** [comment]
Okay, thanks for the answer, added a test.

**Comment by robertoaloi** [comment]
Hi @luos This feature should already be available, but is configuration is probably a bit tricky. Something like this should work for your case:

```
include_dirs:
  - "deps/*/include"
  - "deps"
```

But we could consider this to avoid the manual step. Any thought @jfacorro ?

Also, this should all go away once we integrate with the BSP part.

**Comment by luos** [comment]
Okay, thanks, I'll check it out and report back if it works with that settings.

Yes, it would be better to automagically pick up Erlang MK / Rebar style structure, but if it needs to be configured that is fine as well. :-)

Thanks

**Comment by robertoaloi** [comment]
@luos This PR has been sitting here for a huge amount of time, so sorry about that! Is this change something you still need? Should we solve conflicts?

**Comment by luos** [comment]
Hi,

Let me check it again, I believe maybe it was solved in one of the newer versions as I have not run into this since.

Thanks,

**Comment by luos** [comment]
Hi,

Sorry for the late reply. It still does not work for me. 

Pull this repo: 
https://github.com/rabbitmq/rabbitmq-metronome/

Pull the deps by running `make` or `gmake`, probably it will get stuck but the relevant dep is downloaded fine. 

My `erlang_ls.config` file is the following:

```
include_dirs:
  - "deps/*/include"
  - "deps"
  - "include"
  ```
  
  The error I get is this:
  
kép

Thanks

**Comment by robertoaloi** [comment]
Hi! The following should work:

```
deps_dirs:
  - "deps/*"
include_dirs:
  - "deps"
  - "deps/*/include"
  - "include"
```

I know, it's awkward right now. One entry is for the `include`, the other one for `include_lib`

**Comment by robertoaloi** [comment]
Closing for lack of activity. The proposed solution should work without requiring changes. If that's not the case, feel free to reopen.

**Pull request closed without merging**
