### PR TITLE
Add support for renaming functions

### PR DESCRIPTION
**Pull request by plux**
### Description
Add support for renaming functions

### CODE REVIEW

**Comment by gomoripeti** [comment]
good point in https://github.com/erlang-ls/erlang_ls/pull/962/files#diff-8b95bce4d2827f81806bbfd9649c6aa71564e36f0b693ed981f0b66e37412e9fR222
I think Roberto also mentioned that there needs to be multiple ranges assossiated with a POI.
Although bit arbitrary maybe additional ranges could be stored in the data part, eg an application poi "mod:fun(...)" could have `#{mod_range => _, fun_range => _, colon_range => _}`

**Comment by robertoaloi** [comment]
> good point in https://github.com/erlang-ls/erlang_ls/pull/962/files#diff-8b95bce4d2827f81806bbfd9649c6aa71564e36f0b693ed981f0b66e37412e9fR222
> I think Roberto also mentioned that there needs to be multiple ranges assossiated with a POI.
> Although bit arbitrary maybe additional ranges could be stored in the data part, eg an application poi "mod:fun(...)" could have `#{mod_range => _, fun_range => _, colon_range => _}`

But I guess we can merge this one and follow up, or?

**Review by robertoaloi — APPROVED** [review]

**Comment by robertoaloi** [comment]
Your 2 PRs were conflicting, would you mind rebasing this on `main`?

**Comment by plux** [comment]
> > good point in https://github.com/erlang-ls/erlang_ls/pull/962/files#diff-8b95bce4d2827f81806bbfd9649c6aa71564e36f0b693ed981f0b66e37412e9fR222
> > I think Roberto also mentioned that there needs to be multiple ranges assossiated with a POI.
> > Although bit arbitrary maybe additional ranges could be stored in the data part, eg an application poi "mod:fun(...)" could have `#{mod_range => _, fun_range => _, colon_range => _}`
> 
> But I guess we can merge this one and follow up, or?

Yeah I think this could be merged and then we can improve upon it.

**Comment by plux** [comment]
> Your 2 PRs were conflicting, would you mind rebasing this on `main`?

Rebase done!

**Comment by robertoaloi** [comment]
Thanks! You're on a roll!

**Comment by robertoaloi** [comment]
One thing it would be nice (and hopefully easy) to add is the ability to rename a function starting from any of each function clauses (right now it only works from the top-level clause).

**Comment by plux** [comment]
> One thing it would be nice (and hopefully easy) to add is the ability to rename a function starting from any of each function clauses (right now it only works from the top-level clause).

Good point! I will look into fixing that.

**Pull request merged**
