### PR TITLE
Made els_parser accept -compile(export_all).

### PR DESCRIPTION
**Pull request by pickme467**
This is a fix to the issue:
https://github.com/erlang-ls/erlang_ls/issues/948

### CODE REVIEW

**Review by gomoripeti — APPROVED** [review]
lgtm, maybe could you add a one-liner test case in els_parser_SUITE something like this https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/test/els_parser_SUITE.erl#L71

**Comment by pickme467** [comment]
Test added.

**Comment by robertoaloi** [comment]
@pickme467 Should you rebase on top of the latest `main` and solve the conflict, so we can merge this one?

**Comment by pickme467** [comment]
Hi Roberto,

With your request I realized that the erlang_ls repository doesn't use
master branch, but main branch instead. The error I found is probably a
very old one existing on the master branch. I ran my test on the main
branch and it passed even without my fix, so I guess the main branch is
free from this problem. I use erlang_ls compiled from scratch, so probably
doing the clone it defaulted to master branch and that's why I experienced
problems my fix was addressing. Now I recompiled from the main branch for
me to use it.

Greetings,

Pawel

pt., 26 mar 2021 o 17:04 Roberto Aloi ***@***.***> napisał(a):

**Comment by robertoaloi** [comment]
All right, that makes sense. Thanks for the update!

**Comment by pickme467** [comment]
I have one small proposal. Maybe you could just merge releases to  master
branch, so that clone would give a valuable version out of the box? I never
thought that master branch could be just unusable and that's the reason I
haven't checked if there is another branch used for stable versions.

Greetings,

Pawel

sob., 27 mar 2021 o 10:18 Roberto Aloi ***@***.***>
napisał(a):

**Comment by robertoaloi** [comment]
Hi @pickme467!

Renaming `master` into `main` is an intended choice.
`main` is the default branch name for repositories on GitHub since October 2020:

https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

We renamed the default branch of Erlang LS to `main` since we agree that is not necessary to stick to a less inclusive branch name as `master`. Renaming your local branch should be straightforward:

https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Pull request closed without merging**
