### PR TITLE
Add diagnostics highlighting already bound variables in patterns

### PR DESCRIPTION
**Pull request by gomoripeti**
Inspired by the infamous "pinning operator" and the great blog post of Roberto
on how to write a diagnostics backend. The backend is disabled by default
because of the mixed feedback the pinning-operator idea received.

### CODE REVIEW

**Comment by robertoaloi** [comment]
Ahah, amazing idea! My main feedback would be that the most of the logic could be factored out, sot that it could be reused for implementing #822. In principle, we shouldn't index variables as part of the standard indexing procedure (i.e. for the whole project), but for the current buffer only.

Happy to merge it as is and to tackle eventual refactoring separately. Thanks!

**Comment by robertoaloi** [comment]
Just tried this in both Emacs and VS Code. In Emacs, I like that the hint is not obtrusive. Same in VS Code, where the diagnostic only marks a portion of the variable name, though. Not sure if that's expected.

Screenshot 2021-01-30 at 09 50 28

**Comment by richcarl** [comment]
That was quick, great work! Regardless of whether anyone wants the explicit pinning annotations, I don't se why anyone would oppose having this highlighting on by default.

**Comment by dgud** [comment]
Agree with @richcarl here, great work and make it default even non configure-able.

**Comment by robertoaloi** [comment]
@richcarl @dgud The "disabled by default" approach is what we tend to use for all new features. That's to allow contributors and early adopters that use `main` to try out the feature in their daily code bases. If a feature results stable enough and users enjoy it, than it gets enabled by default prior to a release.

**Comment by gomoripeti** [comment]
thanks for the positive feedback :)
I don't know why VSCode only marks a portion, erlang_ls should send the whole length.
Reworking handling variables sounds good to me. It would be enough to parse only the current function or folding_range for things like jump-to-def or references.

**Pull request merged**
