### PR TITLE
Add support for renaming types

### PR DESCRIPTION
**Pull request by plux**
### Description

Add support for renaming types

### CODE REVIEW

**Comment by plux** [comment]
I'm not sure I'm a fan of DRYing up these changes.

**Comment by robertoaloi** [comment]
> I'm not sure I'm a fan of DRYing up these changes.

Me neither. Maybe add an exception or raise the minimum complexity?

**Comment by plux** [comment]
Cool, I upped the minimum complexity.

**Comment by robertoaloi** [comment]
@plux Do you mind rebasing this branch on top of `main` for a cleaner history?

**Comment by plux** [comment]
> @plux Do you mind rebasing this branch on top of `main` for a cleaner history?

Done

**Comment by robertoaloi** [comment]
Thanks!

**Pull request merged**
