### PR TITLE
Implement URI logic that should work on all systems

### PR DESCRIPTION
**Pull request by filmor**

### CODE REVIEW

**Comment by filmor** [comment]
I'll test this tomorrow again on Windows and will try to work on a proper platform-independent GitHub action for Erlang.

**Comment by filmor** [comment]
Running this manually on Windows works fine, but building is pretty broken right now. I've rolled back those two commits and will create a new PR for them, the change as such works.

**Comment by jfacorro** [comment]
> Running this manually on Windows works fine, but building is pretty broken right now. I've rolled back those two commits and will create a new PR for them, the change as such works.

@filmor Should we close this PR then?

**Comment by filmor** [comment]
No, we should merge this PR ;)

The problem is more that I can't really run the test-suite on Windows right now, but I'll be working on that in a separate PR.

**Comment by jfacorro** [comment]
@robertoaloi Tried this branch. It works on my machine.

**Pull request merged**
