### PR TITLE
Add support for using long names in dap for project node

### PR DESCRIPTION
**Pull request by zsoci**
### Description

If "projectnode" property is a short name, use_long_names = true expands the node name with @hostname.domainname.
This way "projectnode" can be a short name ( ${workspaceFolderBasename} in VSCODE for example) so launch.json can be generic for a repository as no local node name setting is required.

Fixes # .

### CODE REVIEW

**Comment by TheGeorge** [comment]
LGTM
 
 Can you add a test for this, and also make a PR to the VSCode plugin?

**Comment by robertoaloi** [comment]
A test would indeed be appreciated.

**Comment by zsoci** [comment]
Sure, I am on it, just a bit overloaded.

**Comment by robertoaloi** [comment]
Let's get this in (the original functionality is preserved), but please follow up with a test case when you get a chance. Thanks!

**Comment by zsoci** [comment]
Sure. Planned date of the PR with test is on the 18th of june 2021

**Comment by robertoaloi** [comment]
> Sure. Planned date of the PR with test is on the 18th of june 2021

The accuracy! 👯

**Pull request merged**
