### PR TITLE
This is an urgent and useful fix

### PR DESCRIPTION
**Pull request by shuying2244**
For details see Commits.

### CODE REVIEW

**Comment by shuying2244** [comment]
Just like that, the ':' in the 'uri' carried in the request is transcoded to '%3A'.

[2023-10-27T17:05:54.731000+08:00] [debug] Dispatching request [method=<<"textDocument/definition">>] [params=#{<<"position">> => #{<<"character">> => 14,<<"line">> => 1318},<<"textDocument">> => #{<<"uri">> => <<"file:///d%3A/SvnFiles/yf5_dragalia/server/game/player/player_prop.erl">>}}] [els_methods:dispatch/4 L79] <0.147.0>

**Comment by shuying2244** [comment]
Improved 'request references';
Some really cool changes, mainly for looking at references, are comprehensive and fast.

**Comment by plux** [comment]
Care to explain what these changes does?
Also please add tests.

**Comment by shuying2244** [comment]
First about `Added config item 'erls_dirs' to add code not in 'src' to the scope`;
I am currently maintaining a project whose 'erl' files is not in the 'src' directory. 
In order for the plugin to work properly on my project, a new configuration item was added so that directories other than 'src' could be included in the source code search.

**Comment by shuying2244** [comment]
About `':' After being transcoded by the network is '%3A', repair the functi…`;
My client vscode makes a request like '<<"textDocument/definition">>', which carries a params of uri like '<<"file:///d%3A/SvnFiles/yf5_dragalia/server/game/player/player_prop.erl">>',But when the plugin executes 'shallow_index/4', the 'Uri' calculated by 'Uri = els_uri:uri(Fullname)' is '<<"file:///d:/SvnFiles/yf5_dragalia/server/game/player/player_prop.erl">>'.
They don't match, causing the plugin to work abnormally, and my submission is designed to fix that.

**Comment by shuying2244** [comment]
About `'index_dir' now overrides subdirectories, which is useful when lookin… `;
The plugin starts with 'index_dir/4' and 'shallow_index/4' for every file retrieved, but its search level is shallow and there is no way to cover the source code in the subdirectory. This commit aims to solve this problem.

**Comment by shuying2244** [comment]
About `'index_references' added 'macro' and 'record', now they are also very… `;
Fixed the way Kind equals `record`、`record_def_field`、`define` works in `find_references/2`, this `uri_pois_to_locations(find_scoped_references_for_def(Uri, Poi));` is really too slow, now they can use `find_references_for_id(Kind, Key);` like a function.

**Comment by shuying2244** [comment]
All of my changes are the above, not adding any new features, mainly some fixes and optimizations, they change very little code, you can read it in a few minutes; I didn't know what tests to add or how to add them, but I used the modified program locally for a few days, tested most of the functional scenarios, and it worked as expected. In fact, it is very useful now.

**Comment by robertoaloi** [comment]
Hi @shuying2244 and thanks for your contributions. Please try to use a separate PR for each individual feature/contribution since that simplifies reviews and allow easier rollback, when necessary. Also, please use a descriptive title, since "This is an urgent and useful fix" is very generic and does not provide information to the reader. Thanks!

**Comment by shuying2244** [comment]
I get it.

**Pull request closed without merging**
