### PR TITLE
[#237] Remove eflame

### PR DESCRIPTION
**Pull request by robertoaloi**
### Description

We are not going to implement #237 for the time being. Cleaning up the deps, then.

### CODE REVIEW

**Comment by jfacorro** [comment]
`elvis_ core 0.6.0` has some API changes when calling `elvis_core:rock/N`. The configuration is no longer resolved automagically, it now needs to be provided as an argument.

**Comment by robertoaloi** [comment]
Noticed. Fixing.

**Comment by robertoaloi** [comment]
The `elvis_core` documentation was incorrect. Here's a fix for that: https://github.com/inaka/elvis_core/pull/120

**Comment by dgud** [comment]
Hmm now I get problems, what do I need to do, my rebar skills are lacking here.

```
>make
Building escript...
===> Verifying dependencies...
===> Package elvis_core-0.6.0 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /home/dgud/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /home/dgud/.cache/rebar3/hex/default/packages.idx
===> Package not found in registry: {<<"elvis_core">>,<<"0.6.0">>}.
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by robertoaloi** [comment]
@dgud I would start by:

`rm -rf ~/_build`
`rm -rf ~/.cache/rebar3/hex`
`rebar3 update`
`

**Comment by dgud** [comment]
Thanks.

It didn't work, but that got me questioning the world around me.
Updating rebar3 solved the problem. 
From an old 2.6.? to 3.13

**Pull request merged**
