### PR TITLE
[dap] support "attach"

### PR DESCRIPTION
**Pull request by RunyaoZhang**
Different from "launch" which will start a shell, "attach" will attach to an existing shell.
See https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Attach

### Description

Add handle_request for "attach"
Change handle_request for "disconnect" if it was "attach" don't stop the node, only stop breakpoints.

Tests see comment.

Fixes # .

### CODE REVIEW

**Comment by robertoaloi** [comment]
Hi @RunyaoZhang and really thanks for this!
The branch seems to have some linting issues, would you mind looking into those?
Looks good to me, @TheGeorge do you have any feedback on this?
We may want to factor some duplication out, but that can be also done as a follow up.

**Comment by RunyaoZhang** [comment]
For second diff test:
1 Set break point
2 Start shell `rebar3 shell --sname abc@localhost --setcookie COOKIE `
3 Attach
4 `daptoy_fact:fact(2).` ( hit break point )
5 Disconnect
6 Noticed continue (previously not)
7 Attach again
....

**Comment by TheGeorge** [comment]
LGTM let's wait for CI

**Comment by RunyaoZhang** [comment]
Add dap rpc int:n/1 and int: interpreted/0 to fix dialyzer.
(Without these 2 it still work.)
Test same as before.

**Comment by TheGeorge** [comment]
Can you also do a PR to the VSCode plugin?

**Pull request merged**
