### PR TITLE
Handle crashing Mod:format_error gracefully.

### PR DESCRIPTION
**Pull request by kape1395**
I had the following crashes in the ELS log:
```
{function_clause, [
    {compile,format_error,
        [[73,115,115,117,101,32,105,110,32,105,110,99,108,117,100,101,100,32,102,105,108,101,32,40,"1",41,58,32,[123,["undef_parse_transform",44,"stacktrace_transform"],125]]],
        [{file,"compile.erl"},{line,288}]
    },
    {els_compiler_diagnostics,diagnostic,4,[{file,".../erlang_ls/src/els_compiler_diagnostics.erl"},{line,158}]},
    {els_compiler_diagnostics,'-diagnostics/3-lc$^1/1-1-',5,[{file,".../erlang_ls/src/els_compiler_diagnostics.erl"},{line,122}]},
    {els_compiler_diagnostics,'-diagnostics/3-lc$^0/1-0-',4,[{file,".../erlang_ls/src/els_compiler_diagnostics.erl"},{line,129}]},
    {els_compiler_diagnostics,diagnostics,3,[{file,".../erlang_ls/src/els_compiler_diagnostics.erl"},{line,130}]},
    {els_compiler_diagnostics,load_dependency,2,[{file,".../erlang_ls/src/els_compiler_diagnostics.erl"},{line,305}]},
    {els_compiler_diagnostics,'-compile_file/2-lc$^0/1-0-',2,[{file,".../erlang_ls/src/els_compiler_diagnostics.erl"},{line,274}]},
    {els_compiler_diagnostics,compile_file,2,[{file,".../erlang_ls/src/els_compiler_diagnostics.erl"},{line,274}]}
]}
```
I have added these changes and the crash was fixed. But i'm not sure, if the fix should be made in this place. Maybe that's not a root cause.

After a fix, I have strange warnings:
```
-module(...).
-behaviour(supervisor).         % <--- warning is reported here.
```
The text of the warning:
```
Issue in included file (870): {deprecated,
                                  {erlang,now,0},
                                  "Deprecated BIF. See the \"Time and Time Correction in Erlang\" chapter of the ERTS User's Guide for more information."}
```
Althouth there is no calls to `erlang:now/0` in `supervisor.erl`.

I'm using OTP 22.

### CODE REVIEW

**Comment by robertoaloi** [comment]
Interesting, thanks for reporting.

Regarding the new warning, I suspect some "included" file. Is the behaviour including itself a header file? Maybe the current module is including a file and the line where this is reported is off?

It would be good if you could provide a minimal example that triggers this, so we can reproduce it locally.

**Comment by kape1395** [comment]
There is a minimal example (a.erl):
```
-module(a).
-behaviour(supervisor).
```

The warnings are reported by the compiler, but looks like from xref or something?
```
Issue in included file (692): {unused_function,{restart_child,3}}Compiler
Issue in included file (789): {unused_function,{restart_multiple_children,3}}Compiler
Issue in included file (807): {unused_function,{try_again_restart,1}}Compiler
Issue in included file (854): {unused_function,{shutdown,2}}Compiler
Issue in included file (888): {unused_function,{monitor_child,1}}Compiler
Issue in included file (946): {unused_function,{monitor_dynamic_children,2}}Compiler
Issue in included file (960): {unused_function,{wait_dynamic_children,5}}Compiler
Issue in included file (1044): {unused_function,{split_child,2}}Compiler
Issue in included file (1050): {unused_function,{split_ids,3}}Compiler
Issue in included file (1191): {unused_function,{append,2}}Compiler
Issue in included file (1373): {unused_function,{add_restart,1}}Compiler
Issue in included file (1387): {unused_function,{add_restart,3}}Compiler
Issue in included file (1397): {unused_function,{inPeriod,3}}Compiler
Issue in included file (1403): {unused_function,{extract_child,1}}Compiler
Issue in included file (1448): {unused_function,{dyn_fold,3}}Compiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
unknown POSIX errorCompiler
Issue in included file (32): {undefined_function,{handle_info,2}}Compiler
Issue in included file (315): {undefined_function,{start_children,2}}Compiler
Issue in included file (368): {undefined_function,{report_progress,2}}Compiler
Issue in included file (372): {undefined_function,{report_progress,2}}Compiler
Issue in included file (434): {undefined_function,{do_terminate,2}}Compiler
Issue in included file (557): {undefined_function,{restart,2}}Compiler
Issue in included file (570): {spec_fun_undefined,{handle_info,2}}Compiler
Issue in included file (593): {undefined_function,
                                  {terminate_dynamic_children,1}}Compiler
Issue in included file (695): {undefined_function,{do_restart,3}}Compiler
Issue in included file (791): {undefined_function,{start_children,2}}Compiler
Issue in included file (822): {undefined_function,{do_terminate,2}}Compiler
Issue in included file (825): {undefined_function,{do_terminate,2}}Compiler
undefined callback function init/1 (behaviour 'supervisor')Compiler
```

**Comment by kape1395** [comment]
It looks like the problem is only with the `-behaviour` attributes.
`-include` and `-include_lib` are not affected.

The warning underscore is also misaligned, looks similar to the following:
```
-behaviour(locks_leader).
~~~~~~~~~~~~~~~~~~~~~~
```
I.e. "r)." is left not marked.

**Comment by robertoaloi** [comment]
@kape1395 Which client are you using? The one-off error for the warning marker is a known issue in Emacs:

https://github.com/erlang-ls/erlang_ls/issues/705

I just didn't have the time to look into it, yet.

**Comment by robertoaloi** [comment]
The errors are indeed reported by the compiler, but there's a little magic going on, which - in case one of the included files contains an error - tries to give a few more information about the included issue. Ping @alanz

**Comment by kape1395** [comment]
I'm using VSCode.

**Comment by alanz** [comment]
I am seeing something similar, but have been experimenting with a home-grown runtime node so assumed it was related to something I was doing. I will investigate against the current master.

**Comment by robertoaloi** [comment]
Hi @kape1395, I found the reason behind those malformed warnings (fixed in #753 ). So, this may not be necessary. Please keep the branch, though, so we can resume it if this becomes an issue again. The issue about the misalignment will be addressed in #705.

**Pull request closed without merging**
