### PR TITLE
Improve goto definition for variables

### PR DESCRIPTION
**Pull request by plux**
### Description
Improve goto definition for variables

* Use same scoping rules as variable renaming
* No longer limited to only variables inside functions
* Add support for finding variable references

### CODE REVIEW

**Comment by plux** [comment]
Note: Test is failing due to dependency on https://github.com/erlang-ls/erlang_ls/pull/1186 which isn't merged yet.

**Comment by robertoaloi** [comment]
@plux #1186 is now merged. Feel free to rebase.

**Comment by plux** [comment]
rebased :+1:

**Review by robertoaloi — APPROVED** [review]
Amazing stuff, thanks!

**Pull request merged**
