### PR TITLE
[dap] implement evaluate and stacktrace callbacks for dap

### PR DESCRIPTION
**Pull request by TheGeorge**
- implementation for evaluate callback:
  - get values when overing over variables
  - support expressions for watch and repl
- complete stack frames

### CODE REVIEW

**Comment by TheGeorge** [comment]
This is gonna be the last "low-hanging fruit" PR for supporting DAP features, I'll concentrate on tests after this one

**Comment by TheGeorge** [comment]
Screen Shot 2021-02-02 at 6 15 02 PM

**Comment by robertoaloi** [comment]
> This is gonna be the last "low-hanging fruit" PR for supporting DAP features, I'll concentrate on tests after this one

Sounds good! Given that DAP does not interfere with LSP I thought it was good to get all the plumbing in and then to start polishing things and making them production ready. Another thing it would be extremely good is an overview of how the interaction actually works, in VS Code and Emacs. From my experience, once we get that information out (we can do it as an "article" in https://erlang-ls.github.io/), users (including myself) start to play with a feature and come back with suggestions, feature requests and bug fixes. So, the sooner we get that, the better it is.

**Comment by TheGeorge** [comment]
The current plumming of the DAP as special case of the LS is quite dirty. I'm trying to factor the DAP components into a separate app. There are also several corner cases that make the adapter crash, that need to be ironed out. But yeah, excited to get this moving forward

**Pull request merged**
